### ISSUE TITLE
我想问下 中间物料渲染的代码是在哪里呢？

### ISSUE THREAD

**Issue by whenTheMorningDark** [wangyuan389/yunda#2]
我看到的中间部分是通过 iframe 形式引入，地址为 https://www.sunmao-design.top/sunmao/render/#/pages/build/index 我想了解下这地方的代码在哪里呢？

**Comment by wangyuan389** [comment]
你好，渲染器线上版本包含太多个人业务不宜放出，你可以仿照mall-cook自己写个渲染器就行。或者可以加群关注，后面我会出一份干净架构的教程。
